# EKF のパラメータ。説明は README.md の「パラメータ」を参照
/**:
    ros__parameters:
      use_odom: true
      predict_rate: 50.0
      history_length: 1.0
      max_predict_dt: 0.2
      publish_tf: true

      ndt_pose_topic: "ndt_pose"
      odom_topic: "odom"
      initialpose_topic: "initialpose"

      map_frame_id: "map"
      base_frame_id: "base_link"
      lidar_frame_id: "velodyne"

      Q:      [5.0e-2, 5.0e-2, 5.0e-3, 5.0e-2, 5.0e-2, 5.0e-2, 0.05, 1.0e-2] # [x, y, z, roll, pitch, yaw, v, omega]
      P_init: [2.0e-1, 2.0e-1, 2.0e-1, 0.01, 0.01, 0.01, 0.01, 0.01]
      R_ndt:  [1.0e-2, 1.0e-2, 1.0e-2, 0.03, 0.03, 1.0e-3] # [x, y, z, roll, pitch, yaw]（LiDAR）
      R_odom: [2.5e-3, 5.0e-3]  # [v, omega]

      gate_horizontal: 1.0e9
      gate_1d: 1.0e9
      lockout_count: 10
      ndt_delay: 0.0

      odom_covariance_source: "param"
      gate_odom: 1.0e9
      odom_timeout_init: 0.2
      odom_delay: 0.00
